# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f5a2d026ae950285de56dcba422222171066bd1648a995488df3e6131659a85c95683f385f52f2b7bbbdeb93a3936d8a4d9eb9066dd17a7bf47ee9ecb81c4b1

test:
  secret_key_base: 32f5d73af064468e20cb235aff2052b7f21da38f363c96ff6df76d4d9b254b42b040b1e9800d9e52ee0695fb9f817911742df73e567cc036c9f31b42ebfc4cbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
